/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (digimon-world-2003-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80010E90u
#define func_80010E90 BootEntry  /* alias */
